name: Continuous Validation

on:
  schedule:
    - cron: '0 5 * * *'  # Every day at 05:00 UTC
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-core.txt

      - name: Run continuous validation script
        run: python scripts/continuous_validation.py

      - name: Upload evaluation report
        uses: actions/upload-artifact@v3
        with:
          name: validation-report
          path: reports/evaluation/latest_validation.json